### ISSUE TITLE
Add topics in setting.json

### ISSUE THREAD

**Issue by francescasilvano** [thegabriele97/WaterIoT#37]
It is a best practice to add the client id broker and topic into the file setting.json so maybe also this topics can be added in that file
https://github.com/thegabriele97/WaterIoT/blob/3d3f1f02213df82f7fef80dc5c88c0ad94b28eb9/src/services/thingspeakadaptor/app.py#L135-L137
Also here maybe can be passed as arguments too
https://github.com/thegabriele97/WaterIoT/blob/a263036b72cc9eec7cfad3b104fb062d3f43dbfc/src/services/thingspeakadaptor/app.py#L27-L28

**Comment by giovannipollo** [comment]
For me it's a good idea. Let's here what the other thinks!
